
language: objective-c
osx_image: xcode10

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:

    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - xcodebuild clean build -workspace DeepLinkKitExtension.xcworkspace -scheme 'DeepLinkKitExtension iOS' -sdk iphonesimulator -configuration Debug | xcpretty
    - xcodebuild clean build -workspace DeepLinkKitExtension.xcworkspace -scheme 'DeepLinkKitExtension tvOS' -sdk appletvsimulator -configuration Debug | xcpretty
